import type { EVENT_CATEGORIES, EVENT_COLORS } from './constants';

export type EventColor = (typeof EVENT_COLORS)[number];

export type EventCategory = (typeof EVENT_CATEGORIES)[number];

export interface InfoEvent {
  id: string;
  groupId?: string;
  title: string;
  startDate: Date;
  endDate: Date;

  category: EventCategory;
  color: EventColor;
  isAutoGenerated: boolean;

  description?: string;

  employeeIds: string[];
  constructionIds: string[];
}
