import { supabase } from '@/shared/api/supabase';
import type { InfoEvent, EventCategory, EventColor } from '../model/types';
import dayjs from 'dayjs';
import isSameOrAfter from 'dayjs/plugin/isSameOrAfter';
import isBetween from 'dayjs/plugin/isBetween';
import minMax from 'dayjs/plugin/minMax';
import { toSqlDate } from '@/shared/lib/date';

dayjs.extend(isSameOrAfter);
dayjs.extend(isBetween);
dayjs.extend(minMax);

const TABLE_NAME = 'calendar_events';
const JOIN_EMPLOYEES_TABLE = 'calendar_event_employees';
const JOIN_CONSTRUCTIONS_TABLE = 'calendar_event_constructions';

const SELECT_QUERY = `
  *,
  calendar_event_employees ( employee_id ),
  calendar_event_constructions ( construction_id )
`;

const mapEventFromDB = (row: any): InfoEvent => ({
  id: row.id,
  title: row.title || 'Bez tytułu',
  startDate: new Date(row.start_date),
  endDate: new Date(row.end_date),

  category: row.category as EventCategory,
  color: row.color as EventColor,
  isAutoGenerated: row.is_auto_generated,

  description: row.description || '',
  groupId: row.group_id || row.id,

  employeeIds:
    row.calendar_event_employees?.map((r: any) => r.employee_id) || [],
  constructionIds:
    row.calendar_event_constructions?.map((r: any) => r.construction_id) || [],
});

export const createCalendarEvent = async (
  data: Partial<InfoEvent>
): Promise<string> => {
  if (!data.startDate || !data.endDate || !data.title) {
    throw new Error('Brak wymaganych danych (tytuł, data start/koniec)');
  }

  const payload = {
    title: data.title,
    start_date: toSqlDate(data.startDate),
    end_date: toSqlDate(data.endDate),

    category: data.category || 'other',
    color: data.color || 'blue',
    is_auto_generated: data.isAutoGenerated || false,

    description: data.description,
    group_id: data.groupId,
  };

  const { data: createdRecord, error } = await supabase
    .from(TABLE_NAME)
    .insert(payload)
    .select('id')
    .single();

  if (error) throw error;

  const eventId = createdRecord.id;

  if (data.employeeIds && data.employeeIds.length > 0) {
    const employeeRows = data.employeeIds.map((empId) => ({
      event_id: eventId,
      employee_id: empId,
    }));
    const { error: empError } = await supabase
      .from(JOIN_EMPLOYEES_TABLE)
      .insert(employeeRows);
    if (empError) throw empError;
  }

  if (data.constructionIds && data.constructionIds.length > 0) {
    const constructionRows = data.constructionIds.map((constId) => ({
      event_id: eventId,
      construction_id: constId,
    }));
    const { error: constError } = await supabase
      .from(JOIN_CONSTRUCTIONS_TABLE)
      .insert(constructionRows);
    if (constError) throw constError;
  }

  return eventId;
};

export async function updateCalendarEvent(
  id: string,
  data: Partial<InfoEvent>
) {
  const updatePayload: any = {};

  if (data.title) updatePayload.title = data.title;
  if (data.startDate) updatePayload.start_date = toSqlDate(data.startDate);
  if (data.endDate) updatePayload.end_date = toSqlDate(data.endDate);

  if (data.category) updatePayload.category = data.category;
  if (data.color) updatePayload.color = data.color;
  if (data.isAutoGenerated !== undefined)
    updatePayload.is_auto_generated = data.isAutoGenerated;

  if (data.description !== undefined)
    updatePayload.description = data.description;
  if (data.groupId) updatePayload.group_id = data.groupId;

  if (Object.keys(updatePayload).length > 0) {
    const { error } = await supabase
      .from(TABLE_NAME)
      .update(updatePayload)
      .eq('id', id);
    if (error) throw error;
  }

  if (data.employeeIds !== undefined) {
    await supabase.from(JOIN_EMPLOYEES_TABLE).delete().eq('event_id', id);

    if (data.employeeIds.length > 0) {
      const rows = data.employeeIds.map((empId) => ({
        event_id: id,
        employee_id: empId,
      }));
      const { error: empError } = await supabase
        .from(JOIN_EMPLOYEES_TABLE)
        .insert(rows);
      if (empError) throw empError;
    }
  }

  if (data.constructionIds !== undefined) {
    await supabase.from(JOIN_CONSTRUCTIONS_TABLE).delete().eq('event_id', id);

    if (data.constructionIds.length > 0) {
      const rows = data.constructionIds.map((cId) => ({
        event_id: id,
        construction_id: cId,
      }));
      const { error: cError } = await supabase
        .from(JOIN_CONSTRUCTIONS_TABLE)
        .insert(rows);
      if (cError) throw cError;
    }
  }
}

export async function removeCalendarEvent(id: string) {
  const { error } = await supabase.from(TABLE_NAME).delete().eq('id', id);
  if (error) throw error;
}

export async function getCalendarEventsForMonths(
  monthKeys: string[]
): Promise<InfoEvent[]> {
  if (!monthKeys.length) return [];

  const sortedKeys = [...monthKeys].sort();
  const startMonth = sortedKeys[0];
  const endMonth = sortedKeys[sortedKeys.length - 1];

  const minDate = dayjs(startMonth).startOf('month').format('YYYY-MM-DD');
  const maxDate = dayjs(endMonth).endOf('month').format('YYYY-MM-DD');

  const { data, error } = await supabase
    .from(TABLE_NAME)
    .select(SELECT_QUERY)
    .lte('start_date', maxDate)
    .gte('end_date', minDate);

  if (error) throw error;

  return data.map(mapEventFromDB);
}

export const getNearestUpcomingEvents = async (
  limit: number = 10
): Promise<InfoEvent[]> => {
  const today = dayjs().format('YYYY-MM-DD');

  const { data, error } = await supabase
    .from(TABLE_NAME)
    .select(SELECT_QUERY)
    .gte('start_date', today)
    .order('start_date', { ascending: true })
    .limit(limit);

  if (error) throw error;

  return data.map(mapEventFromDB);
};

export const getUpcomingEventsForEmployee = async (
  employeeId: string,
  limit: number = 10
): Promise<InfoEvent[]> => {
  const today = dayjs().format('YYYY-MM-DD');

  const { data, error } = await supabase
    .from(TABLE_NAME)
    .select(
      `
      *,
      calendar_event_employees!inner(employee_id),
      calendar_event_constructions(construction_id)
    `
    )
    .eq('calendar_event_employees.employee_id', employeeId)
    .gte('start_date', today)
    .order('start_date', { ascending: true })
    .limit(limit);

  if (error) throw error;

  return data.map(mapEventFromDB);
};

export const getUpcomingEventsForConstruction = async (
  constructionId: string,
  limit: number = 10
): Promise<InfoEvent[]> => {
  const today = dayjs().format('YYYY-MM-DD');

  const { data, error } = await supabase
    .from(TABLE_NAME)
    .select(
      `
      *,
      calendar_event_employees(employee_id),
      calendar_event_constructions!inner(construction_id)
    `
    )
    .eq('calendar_event_constructions.construction_id', constructionId)
    .gte('start_date', today)
    .order('start_date', { ascending: true })
    .limit(limit);

  if (error) throw error;

  return data.map(mapEventFromDB);
};

export const getEventsForEmployee = async (
  employeeId: string
): Promise<InfoEvent[]> => {
  const { data, error } = await supabase
    .from(TABLE_NAME)
    .select(
      `
      *,
      calendar_event_employees!inner(employee_id),
      calendar_event_constructions(construction_id)
    `
    )
    .eq('calendar_event_employees.employee_id', employeeId)
    .order('start_date', { ascending: false });

  if (error) throw error;

  return data.map(mapEventFromDB);
};
