import type { Dayjs } from 'dayjs';
import type { EVENT_CATEGORIES, EVENT_COLORS } from './const';

export type EventColor = (typeof EVENT_COLORS)[number];

export type EventCategory = (typeof EVENT_CATEGORIES)[number];

export interface InfoEvent {
  id: string;
  groupId?: string;
  title: string;
  startDate: Date;
  endDate: Date;

  category: EventCategory;
  color: EventColor;
  isAutoGenerated: boolean;

  description?: string;

  employeeIds: string[];
  constructionIds: string[];
}

export interface CalendarEvent {
  id?: string;
  groupId?: string;
  date: Dayjs;
  startDate: Dayjs;
  endDate: Dayjs;
  title: string;
  color: EventColor;
  category: EventCategory;
  description?: string;
  isAutoGenerated?: boolean;
  employeeIds: string[];
  constructionIds: string[];
}

export interface CalendarGridProps {
  onMoreClick: (data: CalendarDay) => void;
  monthGrid: CalendarDay[][];
  currentMonth: Dayjs;
  selectDay: Dayjs | null;
  onDayClick: (day: Dayjs) => void;
  isDayInRange: (day: Dayjs) => boolean;
  handleEventClick: (event: CalendarEvent) => void;
}

export interface CalendarDay {
  date: Dayjs;
  events: CalendarEvent[];
  slots?: Record<string, number>;
}
