import type { EventCategory, EventColor } from '@/entities/events';
import type { Dayjs } from 'dayjs';

export interface CalendarEvent {
  id?: string;
  groupId?: string;
  date: Dayjs;
  startDate: Dayjs;
  endDate: Dayjs;
  title: string;
  color: EventColor;
  category: EventCategory;
  description?: string;
  isAutoGenerated?: boolean;
  employeeIds: string[];
  constructionIds: string[];
}
export interface CalendarGridProps {
  onMoreClick: (data: CalendarDay) => void;
  monthGrid: CalendarDay[][];
  currentMonth: Dayjs;
  selectDay: Dayjs | null;
  onDayClick: (day: Dayjs) => void;
  isDayInRange: (day: Dayjs) => boolean;
  handleEventClick: (event: CalendarEvent) => void;
}

export interface CalendarDay {
  date: Dayjs;
  events: CalendarEvent[];
  slots?: Record<string, number>;
}
