import { toSqlDate } from '@/shared/lib/date';
import type { CalendarEventDTO } from './types';
import type { EventCategory, EventColor, InfoEvent } from '../model/types';

export const mapEventFromDB = (row: CalendarEventDTO): InfoEvent => ({
  id: row.id,
  title: row.title || 'Bez tytułu',
  startDate: new Date(row.start_date),
  endDate: new Date(row.end_date),
  category: row.category as EventCategory,
  color: row.color as EventColor,
  isAutoGenerated: row.is_auto_generated,
  description: row.description || '',
  groupId: row.group_id || row.id,

  employeeIds: row.calendar_event_employees?.map((r) => r.employee_id) || [],
  constructionIds:
    row.calendar_event_constructions?.map((r) => r.construction_id) || [],
});

export const mapToEventCreatePayload = (data: Partial<InfoEvent>) => ({
  title: data.title,
  start_date: toSqlDate(data.startDate!),
  end_date: toSqlDate(data.endDate!),
  category: data.category || 'other',
  color: data.color || 'blue',
  is_auto_generated: data.isAutoGenerated || false,
  description: data.description,
  group_id: data.groupId,
});

export const mapToEventUpdatePayload = (data: Partial<InfoEvent>) => {
  const updatePayload: Partial<CalendarEventDTO> = {};

  if (data.title) updatePayload.title = data.title;
  if (data.startDate) {
    updatePayload.start_date = toSqlDate(data.startDate) ?? undefined;
  }
  if (data.endDate) {
    updatePayload.end_date = toSqlDate(data.endDate) ?? undefined;
  }
  if (data.category) updatePayload.category = data.category;
  if (data.color) updatePayload.color = data.color;
  if (data.isAutoGenerated !== undefined)
    updatePayload.is_auto_generated = data.isAutoGenerated;
  if (data.description !== undefined)
    updatePayload.description = data.description;
  if (data.groupId) updatePayload.group_id = data.groupId;

  return updatePayload;
};
