import type { EventCategory, EventColor } from '@/entities/events';
import type { BaseCalendarEvent } from '@/shared/model/types';
export interface UiCalendarEvent extends BaseCalendarEvent {
  title: string;
  color: EventColor;
  category: EventCategory;
  description?: string;
  isAutoGenerated?: boolean;
  groupId?: string;
  employeeIds: string[];
  constructionIds: string[];
}
